language: python
python:
 - "2.7"

addons:
  apt:
    packages:
    - libpcap0.8-dev
    - libnetfilter-queue-dev
    - libssl-dev

notifications:
  irc: "irc.freenode.org#MITMf"

install: "pip install -r requirements.txt"
script: nosetests
