language: python
python:
 - "2.7"
virtualenv:
  system_site_packages: true
sudo: required
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install libpcap0.8-dev libnetfilter-queue-dev"

install: "pip install -r requirements.txt"
script: python tests/basic_tests.py